POST http://localhost:8080/recipes HTTP/1.1
#content-type: application/json

{
  "name": "Chicken Gravy 2",
  "description": "a quick chicken recipe",
  "people": 2,
  "indgredients": [
    {
      "name": "chicken",
      "quantity": 250,
      "unit": "g",
      "type": "poultry"
    },
    {
      "name": "Tomato",
      "quantity": 5,
      "unit": "pc",
      "type": "veggy"
    },
    {
      "name": "Onion",
      "quantity": 2,
      "unit": "pc",
      "type": "veggy"
    },
    {
      "name": "Wheat Parantha",
      "quantity": 4,
      "unit": "pc",
      "type": "wheat"
    }
  ]
}

GET http://localhost:8080/recipes/8cb4c051-7931-476d-b89d-f8f1201c4b5e HTTP/1.1

DELETE http://localhost:8080/recipes/8cb4c051-7931-476d-b89d-f8f1201c4b5e HTTP/1.1

POST http://localhost:8080/recipes/898f9465-9e3b-4375-9262-d3413c6aa229 HTTP/1.1
content-type: application/json

{
  "id": "898f9465-9e3b-4375-9262-d3413c6aa229",
  "name": "Chicken Gravy",
  "description": "a quick chicken recipe",
  "people": 2,
  "indgredients": [
    {
      "name": "chicken",
      "quantity": 250,
      "unit": "g",
      "type": "poultry"
    },
    {
      "name": "Onion",
      "quantity": 2,
      "unit": "pc",
      "type": "veggy"
    },
    {
      "name": "Tomato",
      "quantity": 6,
      "unit": "pc",
      "type": "veggy"
    },
    {
      "name": "Wheat Parantha",
      "quantity": 4,
      "unit": "pc",
      "type": "wheat"
    },
    {
      "name": "Cheese Spread",
      "quantity": 4,
      "unit": "spoon",
      "type": "spread"
    }
  ]
}