// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Product struct {
	ID      int64    `json:"id"`
	Name    string   `json:"name"`
	Company *string  `json:"company"`
	Subtype *string  `json:"subtype"`
	Weight  *float32 `json:"weight"`
	Unit    *string  `json:"unit"`
	Carbs   *float32 `json:"carbs"`
	Protein *float32 `json:"protein"`
	Fiber   *float32 `json:"fiber"`
	Fats    *float32 `json:"fats"`
}
