// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID      int64
	Name    string
	Company pgtype.Text
	Subtype pgtype.Text
	Weight  pgtype.Float4
	Unit    pgtype.Text
	Carbs   pgtype.Float4
	Protein pgtype.Float4
	Fiber   pgtype.Float4
	Fats    pgtype.Float4
}
