// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO PRODUCT (
    name, company, subtype, weight, unit
) VALUES(
    $1, $2, $3, $4, $5
)
RETURNING id, name, company, subtype, weight, unit, carbs, protein, fiber, fats
`

type CreateProductParams struct {
	Name    string   `json:"name"`
	Company *string  `json:"company"`
	Subtype *string  `json:"subtype"`
	Weight  *float32 `json:"weight"`
	Unit    *string  `json:"unit"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Company,
		arg.Subtype,
		arg.Weight,
		arg.Unit,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Subtype,
		&i.Weight,
		&i.Unit,
		&i.Carbs,
		&i.Protein,
		&i.Fiber,
		&i.Fats,
	)
	return &i, err
}

const getAll = `-- name: GetAll :many
SELECT id, name, company, subtype, weight, unit, carbs, protein, fiber, fats FROM PRODUCT
`

func (q *Queries) GetAll(ctx context.Context) ([]*Product, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Subtype,
			&i.Weight,
			&i.Unit,
			&i.Carbs,
			&i.Protein,
			&i.Fiber,
			&i.Fats,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, company, subtype, weight, unit, carbs, protein, fiber, fats FROM PRODUCT
WHERE name=$1 LIMIT 2
`

func (q *Queries) GetProduct(ctx context.Context, name string) (*Product, error) {
	row := q.db.QueryRow(ctx, getProduct, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Subtype,
		&i.Weight,
		&i.Unit,
		&i.Carbs,
		&i.Protein,
		&i.Fiber,
		&i.Fats,
	)
	return &i, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE PRODUCT set name=$1, company=$2, subtype=$3, weight=$4, unit=$5, carbs=$6, protein=$7, fiber=$8, fats=$9 where id=$10 RETURNING id, name, company, subtype, weight, unit, carbs, protein, fiber, fats
`

type UpdateProductParams struct {
	Name    string   `json:"name"`
	Company *string  `json:"company"`
	Subtype *string  `json:"subtype"`
	Weight  *float32 `json:"weight"`
	Unit    *string  `json:"unit"`
	Carbs   *float32 `json:"carbs"`
	Protein *float32 `json:"protein"`
	Fiber   *float32 `json:"fiber"`
	Fats    *float32 `json:"fats"`
	ID      int64    `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Name,
		arg.Company,
		arg.Subtype,
		arg.Weight,
		arg.Unit,
		arg.Carbs,
		arg.Protein,
		arg.Fiber,
		arg.Fats,
		arg.ID,
	)
	return err
}
